[package]
name = "net-utils"
version = "0.1.0"
description = "Common utilities for network applications"
authors = ["Lance Hart <me@lancehart>"]
edition = "2021"
repository = "https://github.com/shipsimfan/lib-net-utils.git"
license = "GPL-3.0-or-later"
publish = false
